notifications:
    email: false
language: python
python:
    - "2.6"
    - "2.7"
install: 
    - pip install -r requirements.txt
    - pip install nose python-coveralls coverage
script: 
    - nosetests tests.py --with-coverage
after_success:
    - coveralls
