language: python
python:
    - "2.6"
    - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
before_script:
    pip install nose python-coveralls coverage
# command to run tests
script: nosetests tests.py --with-coverage
notifications:
    email: false
after_success:
    - coveralls
